spring.application.name=discovery
server.port=8761

# En tant que serveur, Eureka ne doit pas s'enregistrer auprès de lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
